# Google Cloud Build configuration for Techissues Blog
# CLOUD-SAFE: No background processes, no mining, no abuse patterns
# This is a standard Next.js blog deployment

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: techissues
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
    waitFor:
      - 'build'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
    waitFor:
      - 'build'

  # Step 4: Deploy to Cloud Run with strict resource limits
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      # Resource limits to prevent abuse detection
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      # Timeout: 5 minutes max per request (reasonable for a blog)
      - '--timeout'
      - '300'
      # Concurrency limit (prevents resource exhaustion)
      - '--concurrency'
      - '80'
      # CPU only allocated during request processing
      - '--cpu-throttling'
      # Environment variables
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_TELEMETRY_DISABLED=1'
    waitFor:
      - 'push'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  # Use standard E2 machine (not high CPU to avoid suspicion)
  machineType: 'E2_MEDIUM'

# Build timeout (15 minutes - reasonable for Next.js build)
timeout: '900s'
