// English Programming Posts - 20 High Quality Posts
export const programmingPostsEn = [
    {
        title: 'Complete Python Programming Guide for Beginners',
        slug: 'python-complete-beginners-guide',
        tags: ['Python', 'Programming', 'Tutorial', 'Beginners'],
        excerpt: 'Master Python fundamentals from scratch with practical examples and real-world applications that prepare you for the job market.',
        content: `<h2>What is Python?</h2><p>Python is a high-level programming language known for its readability and simplicity. Created by Guido van Rossum and released in 1991, it has become one of the most popular languages worldwide.</p><h2>Why Learn Python?</h2><ul><li>Beginner-friendly with clean syntax</li><li>Huge active community providing support</li><li>Extensive libraries for all domains</li><li>High demand in the job market</li></ul><h2>Python Applications</h2><p>Python is used in web development, artificial intelligence, data analysis, automation, and much more.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'Modern JavaScript Best Practices with ES6+',
        slug: 'modern-javascript-es6-best-practices',
        tags: ['JavaScript', 'ES6', 'Frontend', 'Web Development'],
        excerpt: 'Discover the latest JavaScript features and learn how to write clean, efficient code using ES6+ standards.',
        content: `<h2>Introduction to ES6</h2><p>ES6 or ECMAScript 2015 brought significant improvements to JavaScript, making code more readable and efficient.</p><h2>Variables: let and const</h2><p>Use const for constants and let for variables. Avoid var completely.</p><h2>Arrow Functions</h2><p>A concise and elegant syntax for writing functions with automatic this binding.</p><h2>Template Literals</h2><p>An easy way to combine variables with strings using backticks.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'Building Professional REST APIs with Node.js and Express',
        slug: 'nodejs-express-professional-rest-api',
        tags: ['Node.js', 'Express', 'API', 'Backend'],
        excerpt: 'A comprehensive guide to building robust and secure RESTful APIs using Node.js and Express framework.',
        content: `<h2>What is a REST API?</h2><p>REST is an architectural pattern for designing APIs that rely on HTTP methods.</p><h2>Project Setup</h2><p>Start by creating a new Node.js project and installing Express.</p><h2>Creating Routes</h2><p>Learn how to create endpoints for GET, POST, PUT, DELETE operations.</p><h2>Middleware</h2><p>Use middleware for authentication and error handling.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'React.js: From Zero to Hero Complete Guide',
        slug: 'react-zero-to-hero-guide',
        tags: ['React', 'JavaScript', 'Frontend', 'SPA'],
        excerpt: 'A comprehensive journey into React.js from basic concepts to building complex applications.',
        content: `<h2>Why React?</h2><p>React is the most popular JavaScript library for building interactive user interfaces.</p><h2>Components</h2><p>Learn how to build reusable components.</p><h2>State and Props</h2><p>Understand data management in React and how to pass data between components.</p><h2>Hooks</h2><p>Use useState, useEffect, and other hooks effectively.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
        readingTime: 15,
    },
    {
        title: 'TypeScript Complete Developer Guide',
        slug: 'typescript-developer-complete-guide',
        tags: ['TypeScript', 'JavaScript', 'Types', 'Programming'],
        excerpt: 'Discover the power of TypeScript and how it helps you write safer, more maintainable JavaScript code.',
        content: `<h2>What is TypeScript?</h2><p>TypeScript is a superset of JavaScript that adds static typing to the language.</p><h2>Basic Types</h2><p>Learn about string, number, boolean, array, object, and other types.</p><h2>Interfaces</h2><p>Use interfaces to define the shape of objects.</p><h2>Generics</h2><p>Write flexible, reusable code with Generics.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Git and GitHub Practical Guide for Beginners',
        slug: 'git-github-practical-beginners',
        tags: ['Git', 'GitHub', 'Version Control', 'DevOps'],
        excerpt: 'Learn version control basics with Git and collaborate with your team through GitHub.',
        content: `<h2>What is Git?</h2><p>Git is a free distributed version control system.</p><h2>Basic Commands</h2><p>Learn init, add, commit, push, pull and more.</p><h2>Branches</h2><p>Use branches to work on different features separately.</p><h2>Pull Requests</h2><p>Collaborate with your team through PRs and code review.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'Professional MongoDB Database Design',
        slug: 'mongodb-professional-database-design',
        tags: ['MongoDB', 'NoSQL', 'Database', 'Backend'],
        excerpt: 'Learn to design MongoDB databases professionally with best practices and patterns.',
        content: `<h2>Introduction to MongoDB</h2><p>MongoDB is a flexible and scalable NoSQL document database.</p><h2>Schema Design</h2><p>Learn how to design documents and collections properly.</p><h2>Embedding vs Referencing</h2><p>When to use embedding and when to use references.</p><h2>Indexing</h2><p>Improve query performance with appropriate indexes.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'Docker for Developers: Beginner to Expert',
        slug: 'docker-developers-beginner-expert',
        tags: ['Docker', 'DevOps', 'Containers', 'Deployment'],
        excerpt: 'Explore the world of containers and learn Docker to improve your development and deployment workflow.',
        content: `<h2>What is Docker?</h2><p>Docker is a platform for running applications in isolated containers.</p><h2>Images and Containers</h2><p>Understand the difference between images and containers and how to manage them.</p><h2>Dockerfile</h2><p>Write Dockerfiles to build custom images for your applications.</p><h2>Docker Compose</h2><p>Manage multi-container applications easily.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&q=80',
        readingTime: 14,
    },
    {
        title: 'Object-Oriented Programming in Java',
        slug: 'java-oop-object-oriented-programming',
        tags: ['Java', 'OOP', 'Programming', 'Backend'],
        excerpt: 'A comprehensive guide to understanding OOP principles and applying them in Java.',
        content: `<h2>OOP Principles</h2><p>Learn about Encapsulation, Inheritance, Polymorphism, and Abstraction.</p><h2>Classes and Objects</h2><p>Understand the difference between classes and objects and how to create them.</p><h2>Inheritance</h2><p>Use inheritance to reuse and organize code.</p><h2>Interfaces</h2><p>Learn to use interfaces for abstraction and flexibility.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'CSS Grid and Flexbox Modern Layout Techniques',
        slug: 'css-grid-flexbox-modern-layout',
        tags: ['CSS', 'Grid', 'Flexbox', 'Frontend'],
        excerpt: 'Master modern CSS layout techniques to build responsive and flexible designs.',
        content: `<h2>Flexbox</h2><p>Learn how to align and distribute elements in one dimension.</p><h2>CSS Grid</h2><p>Build complex two-dimensional layouts easily.</p><h2>When to Use Each</h2><p>Understand appropriate cases for Grid vs Flexbox.</p><h2>Responsive Design</h2><p>Make your designs adapt to all screen sizes.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'Next.js 14: Building Blazing Fast Web Applications',
        slug: 'nextjs-14-blazing-fast-web-apps',
        tags: ['Next.js', 'React', 'SSR', 'Full-stack'],
        excerpt: 'Discover the power of Next.js 14 with App Router and Server Components for building fast applications.',
        content: `<h2>What's New in Next.js 14?</h2><p>Major performance improvements, Turbopack, and Server Actions.</p><h2>App Router</h2><p>A new flexible routing system based on folders.</p><h2>Server Components</h2><p>Improve performance by running components on the server.</p><h2>API Routes</h2><p>Build an integrated backend with your Next.js app.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Web Application Security: Complete Guide',
        slug: 'web-application-security-complete',
        tags: ['Security', 'Web', 'OWASP', 'Best Practices'],
        excerpt: 'Learn web security fundamentals and how to protect your applications from common vulnerabilities.',
        content: `<h2>OWASP Top 10</h2><p>Learn about the top 10 security vulnerabilities in web applications.</p><h2>XSS</h2><p>Understand and prevent Cross-Site Scripting attacks.</p><h2>SQL Injection</h2><p>Protect your databases from SQL injection.</p><h2>Authentication</h2><p>Implement a secure and reliable authentication system.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'Algorithms and Data Structures in Python',
        slug: 'algorithms-data-structures-python-guide',
        tags: ['Algorithms', 'Data Structures', 'Python', 'Interview'],
        excerpt: 'Master fundamental algorithms and data structures to prepare for technical interviews.',
        content: `<h2>Data Structures</h2><p>Arrays, Linked Lists, Stacks, Queues, Trees, Graphs.</p><h2>Search Algorithms</h2><p>Linear Search, Binary Search and complexity analysis.</p><h2>Sorting Algorithms</h2><p>Bubble, Selection, Merge, Quick Sort.</p><h2>Dynamic Programming</h2><p>Solve complex problems by breaking them into smaller subproblems.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80',
        readingTime: 16,
    },
    {
        title: 'Vue.js 3 Complete Developer Guide',
        slug: 'vuejs-3-complete-developer-guide',
        tags: ['Vue.js', 'JavaScript', 'Frontend', 'Composition API'],
        excerpt: 'Learn Vue.js 3 with Composition API and build modern interactive applications.',
        content: `<h2>Why Vue.js?</h2><p>An easy-to-learn and flexible framework for building user interfaces.</p><h2>Composition API</h2><p>A new way to organize component logic.</p><h2>Reactive State</h2><p>Manage reactive state with ref and reactive.</p><h2>Pinia</h2><p>Global state management with the modern Pinia library.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1537884944318-390069bb8665?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'SQL Mastery: From Basics to Advanced Queries',
        slug: 'sql-mastery-basics-advanced',
        tags: ['SQL', 'Database', 'MySQL', 'PostgreSQL'],
        excerpt: 'Master SQL for professional handling of relational databases.',
        content: `<h2>SQL Basics</h2><p>SELECT, INSERT, UPDATE, DELETE - fundamental operations.</p><h2>JOINs</h2><p>Connect tables and retrieve related data.</p><h2>Subqueries</h2><p>Nested queries to solve complex problems.</p><h2>Performance</h2><p>Query optimization and indexing strategies.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Flutter: Cross-Platform Mobile App Development',
        slug: 'flutter-cross-platform-mobile-development',
        tags: ['Flutter', 'Dart', 'Mobile', 'Cross-platform'],
        excerpt: 'Build iOS and Android apps from a single codebase using Flutter.',
        content: `<h2>What is Flutter?</h2><p>A Google framework for building cross-platform applications.</p><h2>Widgets</h2><p>Everything in Flutter is a Widget - learn to build them.</p><h2>State Management</h2><p>Use Provider or Riverpod for state management.</p><h2>Navigation</h2><p>Navigate between screens and pass data.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'AWS Cloud Services for Beginners',
        slug: 'aws-cloud-services-beginners',
        tags: ['AWS', 'Cloud', 'DevOps', 'Infrastructure'],
        excerpt: 'Get started with Amazon Web Services and learn the essential cloud services.',
        content: `<h2>What is AWS?</h2><p>The largest cloud platform in the world with hundreds of services.</p><h2>EC2</h2><p>Virtual servers to run your applications.</p><h2>S3</h2><p>Secure and scalable file storage.</p><h2>RDS</h2><p>Fully managed databases.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'GraphQL: The Modern REST Alternative',
        slug: 'graphql-modern-rest-alternative',
        tags: ['GraphQL', 'API', 'Backend', 'Apollo'],
        excerpt: 'Discover GraphQL and how it solves REST problems while improving developer experience.',
        content: `<h2>What is GraphQL?</h2><p>A query language for APIs that gives clients control over data.</p><h2>Queries and Mutations</h2><p>Read and modify data flexibly.</p><h2>Schemas</h2><p>Define data shape and relationships.</p><h2>Apollo Client</h2><p>Manage GraphQL state in React applications.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Linux Commands Every Developer Should Know',
        slug: 'linux-commands-developer-essential',
        tags: ['Linux', 'Terminal', 'DevOps', 'Shell'],
        excerpt: 'Master the Linux command line and essential commands every developer needs.',
        content: `<h2>Why Linux?</h2><p>Most servers run Linux - mastering it is essential for developers.</p><h2>Directory Navigation</h2><p>cd, ls, pwd and basic commands.</p><h2>File Management</h2><p>cp, mv, rm, mkdir and file permissions.</p><h2>Processes</h2><p>ps, top, kill and process management.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'React Performance Optimization Techniques',
        slug: 'react-performance-optimization-techniques',
        tags: ['React', 'Performance', 'Optimization', 'Frontend'],
        excerpt: 'Advanced techniques to optimize React application performance and user experience.',
        content: `<h2>React.memo</h2><p>Prevent unnecessary re-renders of components.</p><h2>useMemo and useCallback</h2><p>Optimize expensive calculations and functions.</p><h2>Code Splitting</h2><p>Split code and load on demand.</p><h2>Virtual Lists</h2><p>Efficiently render large lists.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
        readingTime: 12,
    },
];
