// Arabic Programming Posts - 20 High Quality Posts
export const programmingPostsAr = [
    {
        title: 'مقدمة شاملة في لغة Python للمبتدئين',
        slug: 'python-introduction-beginners',
        tags: ['Python', 'برمجة', 'تعليم', 'مبتدئين'],
        excerpt: 'تعلم أساسيات لغة Python من الصفر مع أمثلة عملية وتطبيقات واقعية تؤهلك لسوق العمل.',
        content: `<h2>ما هي لغة Python؟</h2><p>Python هي لغة برمجة عالية المستوى، تتميز بسهولة القراءة والكتابة. تم تطويرها على يد Guido van Rossum وأُصدرت لأول مرة في عام 1991.</p><h2>لماذا تتعلم Python؟</h2><ul><li>سهلة التعلم للمبتدئين مع syntax واضح</li><li>مجتمع ضخم ونشط يقدم الدعم</li><li>مكتبات متنوعة لجميع المجالات</li><li>مطلوبة بشدة في سوق العمل</li></ul><h2>مجالات استخدام Python</h2><p>تُستخدم Python في تطوير الويب، الذكاء الاصطناعي، تحليل البيانات، الأتمتة، وغيرها الكثير.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'أفضل ممارسات JavaScript الحديثة ES6+',
        slug: 'modern-javascript-es6-practices',
        tags: ['JavaScript', 'ES6', 'Frontend', 'تطوير ويب'],
        excerpt: 'اكتشف أحدث ميزات JavaScript وكيفية كتابة كود نظيف وفعال باستخدام معايير ES6+.',
        content: `<h2>مقدمة في ES6</h2><p>ES6 أو ECMAScript 2015 جلب تحسينات كبيرة للغة JavaScript تجعل الكود أكثر قراءة وكفاءة.</p><h2>المتغيرات: let و const</h2><p>استخدم const للقيم الثابتة و let للمتغيرات. تجنب var نهائياً.</p><h2>Arrow Functions</h2><p>صيغة مختصرة وأنيقة لكتابة الدوال مع binding تلقائي لـ this.</p><h2>Template Literals</h2><p>طريقة سهلة لدمج المتغيرات مع النصوص باستخدام backticks.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'بناء REST API احترافي باستخدام Node.js و Express',
        slug: 'nodejs-express-rest-api',
        tags: ['Node.js', 'Express', 'API', 'Backend'],
        excerpt: 'دليل شامل لبناء واجهة برمجية RESTful قوية وآمنة باستخدام Node.js و Express.',
        content: `<h2>ما هو REST API؟</h2><p>REST هو نمط معماري لتصميم واجهات برمجية تعتمد على HTTP methods.</p><h2>إعداد المشروع</h2><p>ابدأ بإنشاء مشروع Node.js جديد وتثبيت Express.</p><h2>إنشاء الـ Routes</h2><p>تعلم كيفية إنشاء endpoints لـ GET, POST, PUT, DELETE.</p><h2>Middleware</h2><p>استخدم middleware للتحقق من الصلاحيات ومعالجة الأخطاء.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'تعلم React.js من الصفر حتى الاحتراف',
        slug: 'react-js-complete-guide',
        tags: ['React', 'JavaScript', 'Frontend', 'SPA'],
        excerpt: 'رحلة شاملة في عالم React.js من المفاهيم الأساسية إلى بناء تطبيقات معقدة.',
        content: `<h2>لماذا React؟</h2><p>React هي مكتبة JavaScript الأكثر شعبية لبناء واجهات المستخدم التفاعلية.</p><h2>Components</h2><p>تعلم كيفية بناء components قابلة لإعادة الاستخدام.</p><h2>State و Props</h2><p>فهم إدارة البيانات في React وكيفية تمريرها بين المكونات.</p><h2>Hooks</h2><p>استخدم useState و useEffect والـ hooks الأخرى بفعالية.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
        readingTime: 15,
    },
    {
        title: 'دليل TypeScript الشامل للمطورين',
        slug: 'typescript-complete-guide',
        tags: ['TypeScript', 'JavaScript', 'Types', 'برمجة'],
        excerpt: 'اكتشف قوة TypeScript وكيف يساعدك في كتابة كود JavaScript أكثر أماناً وقابلية للصيانة.',
        content: `<h2>ما هو TypeScript؟</h2><p>TypeScript هو superset لـ JavaScript يضيف static typing للغة.</p><h2>أنواع البيانات الأساسية</h2><p>تعرف على string, number, boolean, array, object وأنواع أخرى.</p><h2>Interfaces</h2><p>استخدم interfaces لتعريف شكل الكائنات.</p><h2>Generics</h2><p>اكتب كود مرن وقابل لإعادة الاستخدام مع Generics.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Git و GitHub للمبتدئين: دليل عملي',
        slug: 'git-github-beginners-guide',
        tags: ['Git', 'GitHub', 'Version Control', 'DevOps'],
        excerpt: 'تعلم أساسيات التحكم في الإصدارات باستخدام Git والتعاون مع فريقك عبر GitHub.',
        content: `<h2>ما هو Git؟</h2><p>Git هو نظام تحكم في الإصدارات موزع ومجاني.</p><h2>الأوامر الأساسية</h2><p>تعلم init, add, commit, push, pull والمزيد.</p><h2>Branches</h2><p>استخدم الفروع للعمل على ميزات مختلفة بشكل منفصل.</p><h2>Pull Requests</h2><p>تعاون مع فريقك عبر PR والـ code review.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'تصميم قواعد بيانات MongoDB الاحترافي',
        slug: 'mongodb-database-design',
        tags: ['MongoDB', 'NoSQL', 'Database', 'Backend'],
        excerpt: 'تعلم تصميم قواعد بيانات MongoDB بطريقة احترافية مع أفضل الممارسات والأنماط.',
        content: `<h2>مقدمة في MongoDB</h2><p>MongoDB هي قاعدة بيانات NoSQL وثائقية مرنة وقابلة للتوسع.</p><h2>تصميم Schema</h2><p>تعلم كيفية تصميم documents و collections بشكل صحيح.</p><h2>Embedding vs Referencing</h2><p>متى تستخدم embedding ومتى تستخدم references.</p><h2>Indexing</h2><p>حسّن أداء استعلاماتك باستخدام الفهارس المناسبة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'Docker للمطورين: من المبتدئ إلى المحترف',
        slug: 'docker-developers-guide',
        tags: ['Docker', 'DevOps', 'Containers', 'Deployment'],
        excerpt: 'اكتشف عالم الحاويات وتعلم Docker لتحسين عملية التطوير والنشر.',
        content: `<h2>ما هو Docker؟</h2><p>Docker هي منصة لتشغيل التطبيقات في حاويات معزولة.</p><h2>Images و Containers</h2><p>فهم الفرق بين الصور والحاويات وكيفية إدارتها.</p><h2>Dockerfile</h2><p>اكتب Dockerfile لبناء صور مخصصة لتطبيقاتك.</p><h2>Docker Compose</h2><p>أدر تطبيقات متعددة الحاويات بسهولة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&q=80',
        readingTime: 14,
    },
    {
        title: 'البرمجة الكائنية OOP في Java',
        slug: 'java-oop-programming',
        tags: ['Java', 'OOP', 'برمجة', 'Backend'],
        excerpt: 'دليل شامل لفهم مبادئ البرمجة الكائنية وتطبيقها في Java.',
        content: `<h2>مبادئ OOP</h2><p>تعرف على Encapsulation, Inheritance, Polymorphism, Abstraction.</p><h2>Classes و Objects</h2><p>فهم الفرق بين الفئات والكائنات وكيفية إنشائها.</p><h2>Inheritance</h2><p>استخدم الوراثة لإعادة استخدام الكود وتنظيمه.</p><h2>Interfaces</h2><p>تعلم استخدام الواجهات لتحقيق التجريد والمرونة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'تعلم CSS Grid و Flexbox للتصميم الحديث',
        slug: 'css-grid-flexbox-layout',
        tags: ['CSS', 'Grid', 'Flexbox', 'Frontend'],
        excerpt: 'أتقن تقنيات التخطيط الحديثة في CSS لبناء تصاميم responsive ومرنة.',
        content: `<h2>Flexbox</h2><p>تعلم كيفية محاذاة وتوزيع العناصر في بُعد واحد.</p><h2>CSS Grid</h2><p>بناء تخطيطات ثنائية الأبعاد معقدة بسهولة.</p><h2>متى تستخدم كل منهما</h2><p>فهم الحالات المناسبة لـ Grid vs Flexbox.</p><h2>Responsive Design</h2><p>اجعل تصاميمك تتكيف مع جميع أحجام الشاشات.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'Next.js 14: بناء تطبيقات ويب فائقة السرعة',
        slug: 'nextjs-14-web-apps',
        tags: ['Next.js', 'React', 'SSR', 'Full-stack'],
        excerpt: 'اكتشف قوة Next.js 14 مع App Router وServer Components لبناء تطبيقات سريعة.',
        content: `<h2>ما الجديد في Next.js 14؟</h2><p>تحسينات كبيرة في الأداء و Turbopack وServer Actions.</p><h2>App Router</h2><p>نظام routing جديد ومرن يعتمد على المجلدات.</p><h2>Server Components</h2><p>تحسين الأداء بتشغيل المكونات على السيرفر.</p><h2>API Routes</h2><p>بناء backend مدمج مع تطبيق Next.js.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'الأمان في تطبيقات الويب: دليل شامل',
        slug: 'web-security-guide',
        tags: ['Security', 'أمان', 'Web', 'OWASP'],
        excerpt: 'تعلم أساسيات أمان الويب وكيفية حماية تطبيقاتك من الثغرات الشائعة.',
        content: `<h2>OWASP Top 10</h2><p>تعرف على أهم 10 ثغرات أمنية في تطبيقات الويب.</p><h2>XSS</h2><p>فهم ومنع هجمات Cross-Site Scripting.</p><h2>SQL Injection</h2><p>حماية قواعد البيانات من حقن SQL.</p><h2>Authentication</h2><p>تطبيق نظام مصادقة آمن وموثوق.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'الخوارزميات وهياكل البيانات بلغة Python',
        slug: 'algorithms-data-structures-python',
        tags: ['Algorithms', 'Data Structures', 'Python', 'Interview'],
        excerpt: 'أتقن الخوارزميات وهياكل البيانات الأساسية للتحضير للمقابلات التقنية.',
        content: `<h2>هياكل البيانات</h2><p>Arrays, Linked Lists, Stacks, Queues, Trees, Graphs.</p><h2>خوارزميات البحث</h2><p>Linear Search, Binary Search وتحليل التعقيد.</p><h2>خوارزميات الترتيب</h2><p>Bubble, Selection, Merge, Quick Sort.</p><h2>Dynamic Programming</h2><p>حل المشاكل المعقدة بتقسيمها لمشاكل أصغر.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&q=80',
        readingTime: 16,
    },
    {
        title: 'Vue.js 3: دليل المطور العربي',
        slug: 'vuejs-3-arabic-guide',
        tags: ['Vue.js', 'JavaScript', 'Frontend', 'Composition API'],
        excerpt: 'تعلم Vue.js 3 مع Composition API وبناء تطبيقات تفاعلية حديثة.',
        content: `<h2>لماذا Vue.js؟</h2><p>إطار عمل سهل التعلم ومرن لبناء واجهات المستخدم.</p><h2>Composition API</h2><p>طريقة جديدة لتنظيم منطق المكونات.</p><h2>Reactive State</h2><p>إدارة الحالة التفاعلية مع ref و reactive.</p><h2>Pinia</h2><p>إدارة الحالة العامة مع مكتبة Pinia الحديثة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1537884944318-390069bb8665?w=800&q=80',
        readingTime: 12,
    },
    {
        title: 'تعلم SQL: من الأساسيات إلى الاستعلامات المتقدمة',
        slug: 'sql-basics-to-advanced',
        tags: ['SQL', 'Database', 'MySQL', 'PostgreSQL'],
        excerpt: 'إتقان SQL للتعامل مع قواعد البيانات العلائقية باحترافية.',
        content: `<h2>أساسيات SQL</h2><p>SELECT, INSERT, UPDATE, DELETE - العمليات الأساسية.</p><h2>JOIN</h2><p>ربط الجداول واسترجاع البيانات المترابطة.</p><h2>Subqueries</h2><p>استعلامات فرعية لحل مشاكل معقدة.</p><h2>Performance</h2><p>تحسين أداء الاستعلامات والفهارس.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Flutter: تطوير تطبيقات الموبايل عبر المنصات',
        slug: 'flutter-cross-platform-mobile',
        tags: ['Flutter', 'Dart', 'Mobile', 'Cross-platform'],
        excerpt: 'ابنِ تطبيقات iOS و Android من كود واحد باستخدام Flutter.',
        content: `<h2>ما هو Flutter؟</h2><p>إطار عمل من Google لبناء تطبيقات متعددة المنصات.</p><h2>Widgets</h2><p>كل شيء في Flutter هو Widget - تعلم بناءها.</p><h2>State Management</h2><p>استخدم Provider أو Riverpod لإدارة الحالة.</p><h2>Navigation</h2><p>التنقل بين الشاشات وتمرير البيانات.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
        readingTime: 13,
    },
    {
        title: 'AWS للمبتدئين: خدمات السحابة الأساسية',
        slug: 'aws-cloud-beginners',
        tags: ['AWS', 'Cloud', 'DevOps', 'Infrastructure'],
        excerpt: 'تعرف على خدمات Amazon Web Services الأساسية وابدأ رحلتك مع السحابة.',
        content: `<h2>ما هي AWS؟</h2><p>أكبر منصة سحابية في العالم مع مئات الخدمات.</p><h2>EC2</h2><p>خوادم افتراضية لتشغيل تطبيقاتك.</p><h2>S3</h2><p>تخزين الملفات بشكل آمن وقابل للتوسع.</p><h2>RDS</h2><p>قواعد بيانات مُدارة بالكامل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'GraphQL: بديل REST الحديث',
        slug: 'graphql-modern-api',
        tags: ['GraphQL', 'API', 'Backend', 'Apollo'],
        excerpt: 'اكتشف GraphQL وكيف يحل مشاكل REST ويحسن تجربة المطور.',
        content: `<h2>ما هو GraphQL؟</h2><p>لغة استعلام للـ APIs تمنح العميل التحكم في البيانات.</p><h2>Queries و Mutations</h2><p>قراءة وتعديل البيانات بطريقة مرنة.</p><h2>Schemas</h2><p>تعريف شكل البيانات والعلاقات بينها.</p><h2>Apollo Client</h2><p>إدارة حالة GraphQL في تطبيقات React.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Linux للمطورين: الأوامر الأساسية',
        slug: 'linux-developers-commands',
        tags: ['Linux', 'Terminal', 'DevOps', 'Shell'],
        excerpt: 'أتقن سطر أوامر Linux والأوامر الأساسية التي يحتاجها كل مطور.',
        content: `<h2>لماذا Linux؟</h2><p>معظم الخوادم تعمل بـ Linux - إتقانه ضروري للمطورين.</p><h2>التنقل بين المجلدات</h2><p>cd, ls, pwd والأوامر الأساسية.</p><h2>إدارة الملفات</h2><p>cp, mv, rm, mkdir وصلاحيات الملفات.</p><h2>Processes</h2><p>ps, top, kill وإدارة العمليات.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'تحسين أداء تطبيقات React',
        slug: 'react-performance-optimization',
        tags: ['React', 'Performance', 'Optimization', 'Frontend'],
        excerpt: 'تقنيات متقدمة لتحسين أداء تطبيقات React وتجربة المستخدم.',
        content: `<h2>React.memo</h2><p>منع إعادة render غير الضرورية للمكونات.</p><h2>useMemo و useCallback</h2><p>تحسين الحسابات المكلفة والدوال.</p><h2>Code Splitting</h2><p>تقسيم الكود وتحميله عند الحاجة.</p><h2>Virtual Lists</h2><p>عرض قوائم ضخمة بكفاءة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&q=80',
        readingTime: 12,
    },
];
