// Arabic Device Reviews Posts - 20 High Quality Posts
export const deviceReviewsPostsAr = [
    {
        title: 'مراجعة شاملة لـ iPhone 15 Pro Max',
        slug: 'iphone-15-pro-max-review',
        tags: ['iPhone', 'Apple', 'هاتف', 'مراجعة'],
        excerpt: 'تقييم تفصيلي لأقوى هاتف من Apple مع تحليل المميزات والعيوب.',
        content: `<h2>التصميم والبناء</h2><p>إطار تيتانيوم جديد أخف وزناً وأقوى، مع زر Action Button المبتكر.</p><h2>الشاشة</h2><p>شاشة Super Retina XDR بحجم 6.7 بوصة مع تقنية ProMotion 120Hz.</p><h2>الكاميرا</h2><p>نظام كاميرا Pro بدقة 48 ميجابكسل مع تصوير فيديو احترافي.</p><h2>الأداء</h2><p>معالج A17 Pro الأقوى في عالم الهواتف الذكية.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'مراجعة Samsung Galaxy S24 Ultra',
        slug: 'samsung-galaxy-s24-ultra-review',
        tags: ['Samsung', 'Android', 'Galaxy', 'مراجعة'],
        excerpt: 'نظرة عميقة على هاتف Samsung الرائد مع قدرات الذكاء الاصطناعي.',
        content: `<h2>التصميم</h2><p>إطار تيتانيوم أنيق مع شاشة مسطحة وقلم S Pen مدمج.</p><h2>Galaxy AI</h2><p>ميزات ذكاء اصطناعي مبتكرة للترجمة والتحرير والبحث.</p><h2>الكاميرا</h2><p>كاميرا 200 ميجابكسل مع زوم بصري 5x.</p><h2>البطارية</h2><p>بطارية 5000mAh تدوم طوال اليوم.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'مراجعة MacBook Pro M3 Pro',
        slug: 'macbook-pro-m3-pro-review',
        tags: ['MacBook', 'Apple', 'لابتوب', 'M3'],
        excerpt: 'تقييم شامل لأحدث لابتوب احترافي من Apple بمعالج M3 Pro.',
        content: `<h2>الأداء</h2><p>معالج M3 Pro يقدم أداء استثنائي للمهام الاحترافية.</p><h2>الشاشة</h2><p>شاشة Liquid Retina XDR رائعة مع HDR و ProMotion.</p><h2>البطارية</h2><p>عمر بطارية يصل إلى 22 ساعة.</p><h2>الاتصال</h2><p>منافذ متعددة تشمل HDMI و SD Card وMagSafe.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'مراجعة Sony WH-1000XM5 سماعات الرأس',
        slug: 'sony-wh-1000xm5-headphones-review',
        tags: ['Sony', 'سماعات', 'Headphones', 'ANC'],
        excerpt: 'تجربة أفضل سماعات إلغاء ضوضاء في السوق.',
        content: `<h2>إلغاء الضوضاء</h2><p>أفضل ANC متوفر حالياً مع 8 ميكروفونات.</p><h2>جودة الصوت</h2><p>صوت متوازن وغني مع دعم Hi-Res Audio.</p><h2>الراحة</h2><p>تصميم خفيف ومريح للاستخدام الطويل.</p><h2>البطارية</h2><p>30 ساعة من التشغيل المتواصل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة Dell XPS 15 2024',
        slug: 'dell-xps-15-2024-review',
        tags: ['Dell', 'XPS', 'لابتوب', 'Windows'],
        excerpt: 'تقييم لابتوب Dell الفاخر مع شاشة OLED المذهلة.',
        content: `<h2>الشاشة</h2><p>شاشة OLED 3.5K مع ألوان دقيقة وتباين لا نهائي.</p><h2>التصميم</h2><p>هيكل ألمنيوم فاخر مع لوحة لمس كبيرة.</p><h2>الأداء</h2><p>معالج Intel Core Ultra مع رسوميات قوية.</p><h2>الاتصال</h2><p>منافذ Thunderbolt 4 للاتصال السريع.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'مراجعة Apple Watch Ultra 2',
        slug: 'apple-watch-ultra-2-review',
        tags: ['Apple Watch', 'ساعة', 'Smartwatch', 'رياضة'],
        excerpt: 'تجربة ساعة Apple المصممة للمغامرين والرياضيين المحترفين.',
        content: `<h2>التصميم</h2><p>هيكل تيتانيوم قوي مقاوم للماء حتى 100 متر.</p><h2>الشاشة</h2><p>شاشة أكثر سطوعاً تصل إلى 3000 nits.</p><h2>الميزات</h2><p>GPS مزدوج التردد ومستشعرات متقدمة للصحة.</p><h2>البطارية</h2><p>تدوم حتى 36 ساعة مع الاستخدام العادي.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة PlayStation 5 Slim',
        slug: 'playstation-5-slim-review',
        tags: ['PS5', 'PlayStation', 'ألعاب', 'Sony'],
        excerpt: 'نظرة على النسخة المحسنة من جهاز الألعاب الأكثر مبيعاً.',
        content: `<h2>التصميم الجديد</h2><p>حجم أصغر بنسبة 30% مع مظهر أكثر أناقة.</p><h2>التخزين</h2><p>SSD بسعة 1TB قابل للتوسعة.</p><h2>الأداء</h2><p>نفس الأداء القوي مع تحسينات في الكفاءة.</p><h2>الألعاب</h2><p>دعم 4K/120fps مع Ray Tracing.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'مراجعة iPad Pro M4',
        slug: 'ipad-pro-m4-review',
        tags: ['iPad', 'Apple', 'تابلت', 'M4'],
        excerpt: 'تقييم أقوى جهاز لوحي في العالم بمعالج M4.',
        content: `<h2>الشاشة</h2><p>شاشة OLED Tandem جديدة مع سطوع استثنائي.</p><h2>الأداء</h2><p>معالج M4 الأول من Apple بأداء خارق.</p><h2>التصميم</h2><p>أنحف iPad على الإطلاق بسمك 5.1mm.</p><h2>Apple Pencil Pro</h2><p>دعم لقلم Apple الجديد مع ميزات متقدمة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'مراجعة AirPods Pro 2',
        slug: 'airpods-pro-2-review',
        tags: ['AirPods', 'Apple', 'سماعات', 'Wireless'],
        excerpt: 'تجربة سماعات Apple اللاسلكية مع إلغاء الضوضاء المحسن.',
        content: `<h2>إلغاء الضوضاء</h2><p>ANC محسن بضعف قوة الجيل السابق.</p><h2>جودة الصوت</h2><p>صوت محسن مع دعم Spatial Audio.</p><h2>USB-C</h2><p>منفذ شحن USB-C جديد مع Find My للعلبة.</p><h2>البطارية</h2><p>6 ساعات استماع مع 30 ساعة إضافية في العلبة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'مراجعة Google Pixel 8 Pro',
        slug: 'google-pixel-8-pro-review',
        tags: ['Pixel', 'Google', 'Android', 'كاميرا'],
        excerpt: 'نظرة على هاتف Google الرائد مع قدرات AI المتقدمة.',
        content: `<h2>الكاميرا</h2><p>أفضل كاميرا على Android مع معالجة AI متقدمة.</p><h2>Tensor G3</h2><p>معالج Google الجديد مع قدرات ذكاء اصطناعي محسنة.</p><h2>التحديثات</h2><p>7 سنوات من تحديثات النظام والأمان.</p><h2>الميزات</h2><p>Magic Eraser و Best Take وغيرها من ميزات AI.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'مراجعة ASUS ROG Phone 8 Pro',
        slug: 'asus-rog-phone-8-pro-review',
        tags: ['ASUS', 'ROG', 'Gaming', 'هاتف ألعاب'],
        excerpt: 'تقييم أقوى هاتف ألعاب مع أداء استثنائي.',
        content: `<h2>الأداء</h2><p>Snapdragon 8 Gen 3 مع تبريد متقدم.</p><h2>الشاشة</h2><p>AMOLED 165Hz مع استجابة فائقة.</p><h2>الملحقات</h2><p>AeroActive Cooler ومحفزات خارجية.</p><h2>البطارية</h2><p>5500mAh مع شحن سريع 65W.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة LG C4 OLED TV',
        slug: 'lg-c4-oled-tv-review',
        tags: ['LG', 'OLED', 'تلفزيون', 'شاشة'],
        excerpt: 'تجربة تلفزيون OLED الأكثر مبيعاً لعام 2024.',
        content: `<h2>جودة الصورة</h2><p>ألوان مثالية وأسود حقيقي مع OLED evo.</p><h2>Gaming</h2><p>4 منافذ HDMI 2.1 مع VRR وG-Sync.</p><h2>webOS</h2><p>نظام تشغيل ذكي سهل الاستخدام.</p><h2>التصميم</h2><p>تصميم نحيف وأنيق يناسب أي ديكور.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة Bose QuietComfort Ultra',
        slug: 'bose-quietcomfort-ultra-review',
        tags: ['Bose', 'سماعات', 'ANC', 'Wireless'],
        excerpt: 'تقييم سماعات Bose الجديدة مع صوت Immersive.',
        content: `<h2>إلغاء الضوضاء</h2><p>CustomTune يكيّف الصوت لأذنك.</p><h2>Immersive Audio</h2><p>تجربة صوتية ثلاثية الأبعاد مع head tracking.</p><h2>الراحة</h2><p>تصميم محسن للاستخدام طوال اليوم.</p><h2>البطارية</h2><p>24 ساعة تشغيل متواصل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'مراجعة Nintendo Switch OLED',
        slug: 'nintendo-switch-oled-review',
        tags: ['Nintendo', 'Switch', 'ألعاب', 'محمول'],
        excerpt: 'نظرة على جهاز Nintendo المحمول بشاشة OLED.',
        content: `<h2>الشاشة</h2><p>شاشة OLED 7 بوصة بألوان نابضة بالحياة.</p><h2>التصميم</h2><p>قاعدة محسنة مع LAN port ومسند أفضل.</p><h2>الصوت</h2><p>سماعات محسنة لتجربة أفضل.</p><h2>الألعاب</h2><p>مكتبة ألعاب ضخمة ومتنوعة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'مراجعة Canon EOS R6 Mark II',
        slug: 'canon-eos-r6-mark-ii-review',
        tags: ['Canon', 'كاميرا', 'Photography', 'Mirrorless'],
        excerpt: 'تقييم كاميرا Canon الاحترافية للتصوير الفوتوغرافي والفيديو.',
        content: `<h2>المستشعر</h2><p>مستشعر 24.2 ميجابكسل مع أداء ISO ممتاز.</p><h2>التركيز</h2><p>نظام تركيز تلقائي سريع ودقيق.</p><h2>الفيديو</h2><p>تصوير 4K 60fps و Full HD 180fps.</p><h2>التثبيت</h2><p>تثبيت IBIS حتى 8 وقفات.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'مراجعة Dyson V15 Detect',
        slug: 'dyson-v15-detect-review',
        tags: ['Dyson', 'مكنسة', 'منزل ذكي', 'تنظيف'],
        excerpt: 'تجربة مكنسة Dyson اللاسلكية مع تقنية كشف الغبار.',
        content: `<h2>الليزر</h2><p>ليزر أخضر يكشف الغبار غير المرئي.</p><h2>القوة</h2><p>شفط قوي مع تعديل تلقائي للقوة.</p><h2>الشاشة</h2><p>شاشة LCD تعرض إحصائيات التنظيف.</p><h2>البطارية</h2><p>حتى 60 دقيقة من العمل المتواصل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'مراجعة Logitech MX Master 3S',
        slug: 'logitech-mx-master-3s-review',
        tags: ['Logitech', 'ماوس', 'إنتاجية', 'Wireless'],
        excerpt: 'تقييم أفضل ماوس لاسلكي للإنتاجية.',
        content: `<h2>التصميم</h2><p>تصميم مريح للاستخدام الطويل.</p><h2>MagSpeed</h2><p>عجلة تمرير سريعة ودقيقة.</p><h2>الاتصال</h2><p>Bluetooth و USB receiver مع تبديل سهل.</p><h2>البطارية</h2><p>70 يوم من الاستخدام بشحنة واحدة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'مراجعة Samsung Galaxy Tab S9 Ultra',
        slug: 'samsung-galaxy-tab-s9-ultra-review',
        tags: ['Samsung', 'تابلت', 'Android', 'S Pen'],
        excerpt: 'نظرة على أكبر وأقوى تابلت من Samsung.',
        content: `<h2>الشاشة</h2><p>شاشة عملاقة 14.6 بوصة AMOLED 120Hz.</p><h2>الأداء</h2><p>Snapdragon 8 Gen 2 للأداء الفائق.</p><h2>S Pen</h2><p>قلم S Pen مدمج مع كتابة طبيعية.</p><h2>DeX</h2><p>وضع سطح المكتب للإنتاجية.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة Garmin Fenix 8',
        slug: 'garmin-fenix-8-review',
        tags: ['Garmin', 'ساعة', 'رياضة', 'GPS'],
        excerpt: 'تقييم ساعة Garmin الرياضية للمغامرين.',
        content: `<h2>GPS</h2><p>نظام GPS متعدد النطاقات بدقة عالية.</p><h2>البطارية</h2><p>تدوم حتى أسابيع مع وضع التوفير.</p><h2>الخرائط</h2><p>خرائط طبوغرافية مدمجة.</p><h2>الصحة</h2><p>مستشعرات متقدمة لمتابعة الصحة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'مراجعة Kindle Paperwhite Signature',
        slug: 'kindle-paperwhite-signature-review',
        tags: ['Kindle', 'Amazon', 'قارئ إلكتروني', 'كتب'],
        excerpt: 'تجربة أفضل قارئ إلكتروني للكتب.',
        content: `<h2>الشاشة</h2><p>شاشة 6.8 بوصة E Ink مريحة للعين.</p><h2>الإضاءة</h2><p>إضاءة ذاتية التكيف مع warm light.</p><h2>التخزين</h2><p>32GB لآلاف الكتب.</p><h2>البطارية</h2><p>تدوم حتى 10 أسابيع.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80',
        readingTime: 6,
    },
];
