// English Device Reviews Posts - 20 High Quality Posts
export const deviceReviewsPostsEn = [
    {
        title: 'iPhone 15 Pro Max Complete Review',
        slug: 'iphone-15-pro-max-complete-review',
        tags: ['iPhone', 'Apple', 'Smartphone', 'Review'],
        excerpt: 'Detailed evaluation of Apple\'s most powerful phone with analysis of pros and cons.',
        content: `<h2>Design and Build</h2><p>New titanium frame that's lighter and stronger, with innovative Action Button.</p><h2>Display</h2><p>6.7-inch Super Retina XDR display with ProMotion 120Hz technology.</p><h2>Camera</h2><p>48MP Pro camera system with professional video recording.</p><h2>Performance</h2><p>A17 Pro chip - the most powerful in smartphones.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'Samsung Galaxy S24 Ultra In-Depth Review',
        slug: 'samsung-galaxy-s24-ultra-in-depth',
        tags: ['Samsung', 'Android', 'Galaxy', 'Review'],
        excerpt: 'Deep dive into Samsung\'s flagship phone with AI capabilities.',
        content: `<h2>Design</h2><p>Elegant titanium frame with flat display and built-in S Pen.</p><h2>Galaxy AI</h2><p>Innovative AI features for translation, editing, and search.</p><h2>Camera</h2><p>200MP camera with 5x optical zoom.</p><h2>Battery</h2><p>5000mAh battery lasting all day.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'MacBook Pro M3 Pro Comprehensive Review',
        slug: 'macbook-pro-m3-pro-comprehensive',
        tags: ['MacBook', 'Apple', 'Laptop', 'M3'],
        excerpt: 'Complete evaluation of Apple\'s latest professional laptop with M3 Pro chip.',
        content: `<h2>Performance</h2><p>M3 Pro chip delivers exceptional performance for professional tasks.</p><h2>Display</h2><p>Stunning Liquid Retina XDR display with HDR and ProMotion.</p><h2>Battery</h2><p>Up to 22 hours of battery life.</p><h2>Connectivity</h2><p>Multiple ports including HDMI, SD Card, and MagSafe.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80',
        readingTime: 11,
    },
    {
        title: 'Sony WH-1000XM5 Headphones Review',
        slug: 'sony-wh-1000xm5-headphones',
        tags: ['Sony', 'Headphones', 'ANC', 'Wireless'],
        excerpt: 'Experience the best noise-canceling headphones on the market.',
        content: `<h2>Noise Cancellation</h2><p>Best ANC currently available with 8 microphones.</p><h2>Sound Quality</h2><p>Balanced and rich sound with Hi-Res Audio support.</p><h2>Comfort</h2><p>Lightweight design comfortable for extended use.</p><h2>Battery</h2><p>30 hours of continuous playback.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'Dell XPS 15 2024 Review',
        slug: 'dell-xps-15-2024-review',
        tags: ['Dell', 'XPS', 'Laptop', 'Windows'],
        excerpt: 'Evaluation of Dell\'s premium laptop with stunning OLED display.',
        content: `<h2>Display</h2><p>3.5K OLED display with accurate colors and infinite contrast.</p><h2>Design</h2><p>Premium aluminum chassis with large touchpad.</p><h2>Performance</h2><p>Intel Core Ultra processor with powerful graphics.</p><h2>Connectivity</h2><p>Thunderbolt 4 ports for fast connectivity.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'Apple Watch Ultra 2 Review',
        slug: 'apple-watch-ultra-2-review',
        tags: ['Apple Watch', 'Smartwatch', 'Fitness', 'Sports'],
        excerpt: 'Experience Apple\'s watch designed for adventurers and professional athletes.',
        content: `<h2>Design</h2><p>Strong titanium case water-resistant to 100 meters.</p><h2>Display</h2><p>Brighter display reaching 3000 nits.</p><h2>Features</h2><p>Dual-frequency GPS and advanced health sensors.</p><h2>Battery</h2><p>Lasts up to 36 hours with normal use.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'PlayStation 5 Slim Review',
        slug: 'playstation-5-slim-review',
        tags: ['PS5', 'PlayStation', 'Gaming', 'Sony'],
        excerpt: 'A look at the improved version of the best-selling gaming console.',
        content: `<h2>New Design</h2><p>30% smaller size with more elegant appearance.</p><h2>Storage</h2><p>1TB expandable SSD.</p><h2>Performance</h2><p>Same powerful performance with efficiency improvements.</p><h2>Gaming</h2><p>4K/120fps support with Ray Tracing.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'iPad Pro M4 Review',
        slug: 'ipad-pro-m4-review',
        tags: ['iPad', 'Apple', 'Tablet', 'M4'],
        excerpt: 'Evaluation of the world\'s most powerful tablet with M4 chip.',
        content: `<h2>Display</h2><p>New Tandem OLED display with exceptional brightness.</p><h2>Performance</h2><p>Apple's first M4 chip with incredible performance.</p><h2>Design</h2><p>Thinnest iPad ever at 5.1mm.</p><h2>Apple Pencil Pro</h2><p>Support for new Apple Pencil with advanced features.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'AirPods Pro 2 Complete Review',
        slug: 'airpods-pro-2-complete-review',
        tags: ['AirPods', 'Apple', 'Earbuds', 'Wireless'],
        excerpt: 'Experience Apple\'s wireless earbuds with improved noise cancellation.',
        content: `<h2>Noise Cancellation</h2><p>ANC improved to twice the power of previous generation.</p><h2>Sound Quality</h2><p>Improved sound with Spatial Audio support.</p><h2>USB-C</h2><p>New USB-C charging port with Find My for the case.</p><h2>Battery</h2><p>6 hours listening with 30 additional hours in case.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'Google Pixel 8 Pro Review',
        slug: 'google-pixel-8-pro-review',
        tags: ['Pixel', 'Google', 'Android', 'Camera'],
        excerpt: 'A look at Google\'s flagship phone with advanced AI capabilities.',
        content: `<h2>Camera</h2><p>Best camera on Android with advanced AI processing.</p><h2>Tensor G3</h2><p>Google's new chip with enhanced AI capabilities.</p><h2>Updates</h2><p>7 years of system and security updates.</p><h2>Features</h2><p>Magic Eraser, Best Take, and other AI features.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'ASUS ROG Phone 8 Pro Gaming Phone Review',
        slug: 'asus-rog-phone-8-pro-gaming',
        tags: ['ASUS', 'ROG', 'Gaming', 'Phone'],
        excerpt: 'Evaluation of the most powerful gaming phone with exceptional performance.',
        content: `<h2>Performance</h2><p>Snapdragon 8 Gen 3 with advanced cooling.</p><h2>Display</h2><p>165Hz AMOLED with ultra-responsive touch.</p><h2>Accessories</h2><p>AeroActive Cooler and external triggers.</p><h2>Battery</h2><p>5500mAh with 65W fast charging.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'LG C4 OLED TV Review',
        slug: 'lg-c4-oled-tv-review',
        tags: ['LG', 'OLED', 'TV', 'Display'],
        excerpt: 'Experience the best-selling OLED TV of 2024.',
        content: `<h2>Picture Quality</h2><p>Perfect colors and true blacks with OLED evo.</p><h2>Gaming</h2><p>4 HDMI 2.1 ports with VRR and G-Sync.</p><h2>webOS</h2><p>User-friendly smart operating system.</p><h2>Design</h2><p>Slim and elegant design fits any decor.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'Bose QuietComfort Ultra Headphones Review',
        slug: 'bose-quietcomfort-ultra-headphones',
        tags: ['Bose', 'Headphones', 'ANC', 'Wireless'],
        excerpt: 'Evaluation of Bose\'s new headphones with Immersive Audio.',
        content: `<h2>Noise Cancellation</h2><p>CustomTune adapts sound to your ears.</p><h2>Immersive Audio</h2><p>3D audio experience with head tracking.</p><h2>Comfort</h2><p>Improved design for all-day use.</p><h2>Battery</h2><p>24 hours continuous playback.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'Nintendo Switch OLED Review',
        slug: 'nintendo-switch-oled-review',
        tags: ['Nintendo', 'Switch', 'Gaming', 'Portable'],
        excerpt: 'A look at Nintendo\'s portable console with OLED screen.',
        content: `<h2>Display</h2><p>7-inch OLED screen with vibrant colors.</p><h2>Design</h2><p>Improved dock with LAN port and better kickstand.</p><h2>Audio</h2><p>Enhanced speakers for better experience.</p><h2>Games</h2><p>Huge and diverse game library.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'Canon EOS R6 Mark II Camera Review',
        slug: 'canon-eos-r6-mark-ii-camera',
        tags: ['Canon', 'Camera', 'Photography', 'Mirrorless'],
        excerpt: 'Evaluation of Canon\'s professional camera for photography and video.',
        content: `<h2>Sensor</h2><p>24.2MP sensor with excellent ISO performance.</p><h2>Autofocus</h2><p>Fast and accurate autofocus system.</p><h2>Video</h2><p>4K 60fps and Full HD 180fps recording.</p><h2>Stabilization</h2><p>IBIS up to 8 stops of stabilization.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80',
        readingTime: 10,
    },
    {
        title: 'Dyson V15 Detect Vacuum Review',
        slug: 'dyson-v15-detect-vacuum-review',
        tags: ['Dyson', 'Vacuum', 'Smart Home', 'Cleaning'],
        excerpt: 'Experience Dyson\'s cordless vacuum with dust detection technology.',
        content: `<h2>Laser</h2><p>Green laser reveals invisible dust.</p><h2>Power</h2><p>Strong suction with automatic power adjustment.</p><h2>Display</h2><p>LCD screen shows cleaning statistics.</p><h2>Battery</h2><p>Up to 60 minutes of continuous cleaning.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'Logitech MX Master 3S Mouse Review',
        slug: 'logitech-mx-master-3s-mouse-review',
        tags: ['Logitech', 'Mouse', 'Productivity', 'Wireless'],
        excerpt: 'Evaluation of the best wireless mouse for productivity.',
        content: `<h2>Design</h2><p>Ergonomic design for extended use.</p><h2>MagSpeed</h2><p>Fast and precise scroll wheel.</p><h2>Connectivity</h2><p>Bluetooth and USB receiver with easy switching.</p><h2>Battery</h2><p>70 days of use on a single charge.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'Samsung Galaxy Tab S9 Ultra Review',
        slug: 'samsung-galaxy-tab-s9-ultra-review',
        tags: ['Samsung', 'Tablet', 'Android', 'S Pen'],
        excerpt: 'A look at Samsung\'s largest and most powerful tablet.',
        content: `<h2>Display</h2><p>Giant 14.6-inch AMOLED 120Hz screen.</p><h2>Performance</h2><p>Snapdragon 8 Gen 2 for superior performance.</p><h2>S Pen</h2><p>Built-in S Pen with natural writing.</p><h2>DeX</h2><p>Desktop mode for productivity.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'Garmin Fenix 8 Sports Watch Review',
        slug: 'garmin-fenix-8-sports-watch-review',
        tags: ['Garmin', 'Smartwatch', 'Sports', 'GPS'],
        excerpt: 'Evaluation of Garmin\'s sports watch for adventurers.',
        content: `<h2>GPS</h2><p>Multi-band GPS system with high accuracy.</p><h2>Battery</h2><p>Lasts up to weeks in power saving mode.</p><h2>Maps</h2><p>Built-in topographic maps.</p><h2>Health</h2><p>Advanced sensors for health monitoring.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'Kindle Paperwhite Signature Edition Review',
        slug: 'kindle-paperwhite-signature-review',
        tags: ['Kindle', 'Amazon', 'E-Reader', 'Books'],
        excerpt: 'Experience the best e-reader for books.',
        content: `<h2>Display</h2><p>6.8-inch E Ink screen easy on the eyes.</p><h2>Lighting</h2><p>Self-adjusting light with warm light option.</p><h2>Storage</h2><p>32GB for thousands of books.</p><h2>Battery</h2><p>Lasts up to 10 weeks.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80',
        readingTime: 6,
    },
];
