// Arabic Tech Issues Posts - 20 High Quality Posts
export const techIssuesPostsAr = [
    {
        title: 'حل مشكلة بطء Windows 10 و 11 بشكل نهائي',
        slug: 'fix-slow-windows-10-11',
        tags: ['Windows', 'Performance', 'تحسين', 'مشاكل'],
        excerpt: 'خطوات عملية ومجربة لتسريع جهاز الكمبيوتر الذي يعمل بنظام Windows.',
        content: `<h2>الأسباب الشائعة لبطء Windows</h2><p>عدة عوامل تؤثر على أداء النظام منها البرامج الخلفية والملفات المؤقتة.</p><h2>تعطيل برامج بدء التشغيل</h2><p>افتح Task Manager واذهب إلى Startup لتعطيل البرامج غير الضرورية.</p><h2>تنظيف الملفات المؤقتة</h2><p>استخدم Disk Cleanup أو Storage Sense لتحرير المساحة.</p><h2>تحديث التعريفات</h2><p>تأكد من تحديث جميع drivers خاصة كروت الشاشة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1587831990711-23ca6441447b?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'إصلاح مشاكل WiFi في الهواتف الذكية',
        slug: 'fix-wifi-issues-smartphones',
        tags: ['WiFi', 'Mobile', 'شبكات', 'أندرويد'],
        excerpt: 'حلول فعالة لمشاكل الاتصال بالواي فاي في هواتف Android و iPhone.',
        content: `<h2>المشاكل الشائعة</h2><p>عدم الاتصال، انقطاع متكرر، أو بطء في السرعة.</p><h2>إعادة ضبط الشبكة</h2><p>جرب نسيان الشبكة وإعادة الاتصال بها من جديد.</p><h2>تحديث النظام</h2><p>تأكد من تحديث نظام التشغيل لآخر إصدار.</p><h2>إعادة ضبط إعدادات الشبكة</h2><p>كحل أخير يمكنك Reset Network Settings.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1606904825846-647eb07f5be2?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'حل الشاشة الزرقاء BSOD في Windows',
        slug: 'fix-blue-screen-bsod-windows',
        tags: ['Windows', 'BSOD', 'أخطاء', 'Hardware'],
        excerpt: 'دليل شامل لفهم وحل مشكلة الشاشة الزرقاء Blue Screen of Death.',
        content: `<h2>ما هي الشاشة الزرقاء؟</h2><p>رسالة خطأ تظهر عند حدوث مشكلة خطيرة تمنع Windows من العمل.</p><h2>قراءة رمز الخطأ</h2><p>كل شاشة زرقاء تحتوي على رمز خطأ يساعد في التشخيص.</p><h2>فحص الذاكرة RAM</h2><p>استخدم Windows Memory Diagnostic لفحص الذاكرة.</p><h2>تحديث أو إزالة التعريفات</h2><p>التعريفات السيئة سبب شائع للـ BSOD.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'حل مشكلة ارتفاع حرارة اللابتوب',
        slug: 'fix-laptop-overheating',
        tags: ['Laptop', 'Overheating', 'Hardware', 'صيانة'],
        excerpt: 'أسباب ارتفاع حرارة اللابتوب وطرق التبريد الفعالة.',
        content: `<h2>أسباب ارتفاع الحرارة</h2><p>انسداد فتحات التهوية، تراكم الغبار، أو معجون حراري قديم.</p><h2>تنظيف الفتحات</h2><p>استخدم هواء مضغوط لتنظيف فتحات التهوية.</p><h2>قاعدة تبريد</h2><p>استخدم cooling pad لتحسين تدفق الهواء.</p><h2>تقليل الأحمال</h2><p>أغلق البرامج غير الضرورية وتحقق من استخدام CPU.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'استرجاع الملفات المحذوفة من الكمبيوتر',
        slug: 'recover-deleted-files-computer',
        tags: ['Data Recovery', 'ملفات', 'استعادة', 'Windows'],
        excerpt: 'طرق فعالة لاسترجاع الملفات المحذوفة عن طريق الخطأ.',
        content: `<h2>سلة المهملات أولاً</h2><p>تحقق من Recycle Bin قبل أي خطوة أخرى.</p><h2>النسخ الاحتياطية</h2><p>تحقق من File History أو نقاط الاستعادة.</p><h2>برامج الاسترجاع</h2><p>استخدم برامج مثل Recuva أو TestDisk.</p><h2>نصائح مهمة</h2><p>لا تكتب بيانات جديدة على القرص لزيادة فرص الاسترجاع.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'حل مشاكل البلوتوث في Windows',
        slug: 'fix-bluetooth-issues-windows',
        tags: ['Bluetooth', 'Windows', 'سماعات', 'أجهزة'],
        excerpt: 'إصلاح مشاكل الاتصال والإقران في البلوتوث.',
        content: `<h2>تشغيل مستكشف الأخطاء</h2><p>استخدم Bluetooth troubleshooter المدمج في Windows.</p><h2>إعادة تثبيت التعريف</h2><p>احذف تعريف البلوتوث وأعد تثبيته من Device Manager.</p><h2>إعادة الإقران</h2><p>احذف الجهاز وأعد إقرانه من جديد.</p><h2>التحقق من الخدمات</h2><p>تأكد من تشغيل Bluetooth Support Service.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'إصلاح مشكلة عدم الإقلاع في Windows',
        slug: 'fix-windows-boot-problems',
        tags: ['Windows', 'Boot', 'إقلاع', 'إصلاح'],
        excerpt: 'حلول لمشاكل عدم بدء تشغيل Windows بشكل صحيح.',
        content: `<h2>الوضع الآمن</h2><p>جرب الدخول إلى Safe Mode لتشخيص المشكلة.</p><h2>إصلاح بدء التشغيل</h2><p>استخدم Startup Repair من Recovery Environment.</p><h2>أوامر الإصلاح</h2><p>استخدم bootrec /fixmbr و bootrec /fixboot.</p><h2>استعادة النظام</h2><p>جرب System Restore لنقطة سابقة تعمل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
        readingTime: 9,
    },
    {
        title: 'حل مشكلة نفاد البطارية بسرعة في الهاتف',
        slug: 'fix-phone-battery-drain',
        tags: ['Battery', 'Mobile', 'بطارية', 'Android'],
        excerpt: 'أسباب استنزاف البطارية وطرق إطالة عمرها.',
        content: `<h2>التطبيقات المستهلكة</h2><p>تحقق من Battery Usage لمعرفة التطبيقات المستهلكة.</p><h2>تقليل السطوع</h2><p>استخدم السطوع التلقائي أو خفض السطوع يدوياً.</p><h2>إيقاف الخدمات غير المستخدمة</h2><p>أوقف GPS وBluetooth عند عدم الاستخدام.</p><h2>وضع توفير الطاقة</h2><p>فعّل Battery Saver عند انخفاض البطارية.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'إصلاح مشاكل الصوت في الكمبيوتر',
        slug: 'fix-computer-audio-issues',
        tags: ['Audio', 'Sound', 'صوت', 'Windows'],
        excerpt: 'حلول لمشاكل انعدام الصوت أو ضعفه في الكمبيوتر.',
        content: `<h2>التحقق من مستوى الصوت</h2><p>تأكد من عدم كتم الصوت في Windows وفي البرنامج.</p><h2>جهاز الإخراج الصحيح</h2><p>تحقق من اختيار جهاز الصوت الصحيح من الإعدادات.</p><h2>تحديث تعريف الصوت</h2><p>حدث أو أعد تثبيت Audio driver.</p><h2>Audio Services</h2><p>تأكد من تشغيل Windows Audio Service.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'حل مشاكل الطابعة والاتصال بها',
        slug: 'fix-printer-connection-issues',
        tags: ['Printer', 'طابعة', 'Windows', 'USB'],
        excerpt: 'إصلاح مشاكل الطابعة من عدم الاتصال إلى جودة الطباعة.',
        content: `<h2>التحقق من الاتصال</h2><p>تأكد من توصيل الكابلات أو اتصال WiFi.</p><h2>إعادة تثبيت الطابعة</h2><p>احذف الطابعة وأضفها من جديد.</p><h2>تحديث التعريفات</h2><p>حمّل أحدث تعريفات من موقع الشركة المصنعة.</p><h2>Print Spooler</h2><p>أعد تشغيل خدمة Print Spooler.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'حل مشكلة الإنترنت البطيء',
        slug: 'fix-slow-internet-connection',
        tags: ['Internet', 'Speed', 'إنترنت', 'Router'],
        excerpt: 'خطوات لتحسين سرعة الإنترنت وحل مشاكل البطء.',
        content: `<h2>اختبار السرعة</h2><p>استخدم speedtest.net لقياس السرعة الفعلية.</p><h2>إعادة تشغيل الراوتر</h2><p>أوقف الراوتر 30 ثانية ثم أعد تشغيله.</p><h2>تغيير قناة WiFi</h2><p>غيّر قناة WiFi لتجنب التداخل.</p><h2>DNS بديل</h2><p>استخدم Google DNS أو Cloudflare DNS.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'إزالة الفيروسات والبرمجيات الخبيثة',
        slug: 'remove-viruses-malware',
        tags: ['Virus', 'Malware', 'Security', 'حماية'],
        excerpt: 'دليل شامل لإزالة الفيروسات وحماية جهازك.',
        content: `<h2>علامات الإصابة</h2><p>بطء مفاجئ، إعلانات منبثقة، أو برامج غير معروفة.</p><h2>Windows Defender</h2><p>قم بفحص كامل باستخدام Windows Security.</p><h2>Malwarebytes</h2><p>استخدم Malwarebytes للكشف عن البرمجيات الخبيثة.</p><h2>الوضع الآمن</h2><p>قم بالفحص من Safe Mode للنتائج الأفضل.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
        readingTime: 8,
    },
    {
        title: 'حل مشاكل تحديثات Windows',
        slug: 'fix-windows-update-issues',
        tags: ['Windows Update', 'تحديثات', 'أخطاء', 'Windows'],
        excerpt: 'إصلاح أخطاء Windows Update وفشل التحديثات.',
        content: `<h2>مستكشف الأخطاء</h2><p>شغّل Windows Update Troubleshooter.</p><h2>إعادة تعيين المكونات</h2><p>أعد تعيين Windows Update components.</p><h2>تحرير المساحة</h2><p>تأكد من وجود مساحة كافية للتحديث.</p><h2>التحديث اليدوي</h2><p>حمّل التحديث يدوياً من Microsoft Catalog.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=800&q=80',
        readingTime: 7,
    },
    {
        title: 'حل مشكلة الشاشة السوداء في Windows',
        slug: 'fix-black-screen-windows',
        tags: ['Black Screen', 'شاشة', 'Windows', 'Display'],
        excerpt: 'أسباب وحلول مشكلة الشاشة السوداء عند تشغيل الكمبيوتر.',
        content: `<h2>الأسباب المحتملة</h2><p>مشاكل في التعريفات، التوصيلات، أو النظام.</p><h2>التحقق من التوصيلات</h2><p>تأكد من توصيل كابل الشاشة بشكل صحيح.</p><h2>تعريف كرت الشاشة</h2><p>جرب الوضع الآمن وأعد تثبيت GPU driver.</p><h2>Explorer.exe</h2><p>جرب تشغيل explorer.exe من Task Manager.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'إصلاح مشاكل التخزين الممتلئ',
        slug: 'fix-storage-full-issues',
        tags: ['Storage', 'تخزين', 'مساحة', 'Cleanup'],
        excerpt: 'تحرير مساحة التخزين وإدارتها بشكل فعال.',
        content: `<h2>Disk Cleanup</h2><p>استخدم أداة Disk Cleanup المدمجة.</p><h2>حذف الملفات المؤقتة</h2><p>امسح مجلد Temp والملفات المؤقتة.</p><h2>إلغاء تثبيت البرامج</h2><p>أزل البرامج غير المستخدمة.</p><h2>التخزين السحابي</h2><p>انقل الملفات الكبيرة إلى السحابة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'حل مشاكل تطبيقات Android لا تعمل',
        slug: 'fix-android-apps-not-working',
        tags: ['Android', 'Apps', 'تطبيقات', 'Crash'],
        excerpt: 'إصلاح تطبيقات Android التي تتوقف أو لا تعمل بشكل صحيح.',
        content: `<h2>مسح ذاكرة التخزين المؤقت</h2><p>امسح Cache للتطبيق من الإعدادات.</p><h2>تحديث التطبيق</h2><p>تأكد من تثبيت آخر إصدار من Play Store.</p><h2>إعادة تثبيت التطبيق</h2><p>احذف التطبيق وأعد تثبيته.</p><h2>التحقق من الصلاحيات</h2><p>تأكد من منح التطبيق الصلاحيات المطلوبة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'حل مشكلة الماوس أو لوحة المفاتيح لا تعمل',
        slug: 'fix-mouse-keyboard-not-working',
        tags: ['Mouse', 'Keyboard', 'USB', 'Hardware'],
        excerpt: 'إصلاح مشاكل الماوس ولوحة المفاتيح الشائعة.',
        content: `<h2>التحقق من التوصيل</h2><p>جرب منفذ USB آخر أو أعد إقران البلوتوث.</p><h2>تعريفات الأجهزة</h2><p>حدث أو أعد تثبيت التعريفات من Device Manager.</p><h2>تنظيف الأجهزة</h2><p>نظف الأجهزة من الغبار والأوساخ.</p><h2>اختبار على جهاز آخر</h2><p>جرب الجهاز على كمبيوتر آخر للتأكد من سلامته.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'إصلاح مشاكل iCloud و Apple ID',
        slug: 'fix-icloud-apple-id-issues',
        tags: ['iCloud', 'Apple', 'iOS', 'Sync'],
        excerpt: 'حلول لمشاكل iCloud والمزامنة وتسجيل الدخول.',
        content: `<h2>تسجيل الخروج والدخول</h2><p>جرب تسجيل الخروج من iCloud ثم الدخول مجدداً.</p><h2>التحقق من الإنترنت</h2><p>تأكد من اتصال الإنترنت المستقر.</p><h2>تحديث النظام</h2><p>حدث iOS أو macOS لآخر إصدار.</p><h2>إعادة ضبط المزامنة</h2><p>أوقف وأعد تشغيل خدمات iCloud المحددة.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1523206489230-c012c64b2b48?w=800&q=80',
        readingTime: 6,
    },
    {
        title: 'حل مشاكل Chrome والمتصفحات',
        slug: 'fix-chrome-browser-issues',
        tags: ['Chrome', 'Browser', 'متصفح', 'Extensions'],
        excerpt: 'إصلاح مشاكل Chrome من البطء إلى عدم الاستجابة.',
        content: `<h2>مسح بيانات التصفح</h2><p>امسح Cache وCookies من الإعدادات.</p><h2>تعطيل الإضافات</h2><p>عطل Extensions للتحقق من التعارضات.</p><h2>إعادة تعيين Chrome</h2><p>أعد تعيين المتصفح لإعداداته الافتراضية.</p><h2>تحديث Chrome</h2><p>تأكد من تثبيت آخر إصدار من المتصفح.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=800&q=80',
        readingTime: 5,
    },
    {
        title: 'حل مشاكل التجمد والتهنيج في الكمبيوتر',
        slug: 'fix-computer-freezing-hanging',
        tags: ['Freeze', 'Hang', 'تجمد', 'Performance'],
        excerpt: 'أسباب وحلول تجمد الكمبيوتر وعدم الاستجابة.',
        content: `<h2>التحقق من الموارد</h2><p>افتح Task Manager لمعرفة ما يستهلك الموارد.</p><h2>فحص الهارد ديسك</h2><p>استخدم chkdsk لفحص أخطاء القرص.</p><h2>اختبار الذاكرة</h2><p>افحص RAM باستخدام Windows Memory Diagnostic.</p><h2>التحقق من الحرارة</h2><p>راقب درجات الحرارة لتجنب الـ throttling.</p>`,
        coverImage: 'https://images.unsplash.com/photo-1537498425277-c283d32ef9db?w=800&q=80',
        readingTime: 7,
    },
];
